name: PR license scan

on:
  pull_request_target: # this is safe as these scans do not execute provided code
  push:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}

    steps:
      - uses: actions/checkout@v3

      - name: Download FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa --version
          
      - name: FOSSA Analyze Output
        run: |
          fossa analyze -o | jq
      
      - name: FOSSA Analyze 
        run: |
          fossa analyze
